# Generated by Django 3.2.3 on 2021-05-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cart_productidsold'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ProductNameSold',
            field=models.CharField(default=0, max_length=250, verbose_name='Название продукта'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='ProductId',
            field=models.CharField(default=0, max_length=250, verbose_name='ID товара'),
        ),
    ]
