# Generated by Django 3.2.3 on 2021-05-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210529_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='ProductMetaDescription',
            field=models.TextField(verbose_name='MetaDescription'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='ProductMetaKeywords',
            field=models.TextField(verbose_name='MetaKeywords'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='ProductMetaTittle',
            field=models.CharField(max_length=250, verbose_name='MetaTittle'),
        ),
    ]
