# Generated by Django 3.2.3 on 2021-05-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210529_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='ProductImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images/', verbose_name='Изображение'),
        ),
    ]
