# Generated by Django 3.2.3 on 2021-05-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_catalog_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='ProductImage',
            field=models.ImageField(blank=True, default='product_images/no-image.jpg', null=True, upload_to='product_images', verbose_name='Изображение'),
        ),
    ]
