# Generated by Django 3.2.3 on 2021-05-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_catalog_productfeatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='ProductFeatures',
            field=models.TextField(choices=[('MI_L', 'Легкая техника'), ('MI_I', 'Встраиваемая техника'), ('CP_F', 'Готовые ПК'), ('LT', 'Ноутбуки'), ('IM_PORT', 'Портативные инструменты'), ('IM_HARD', 'Тяжелые инструменты'), ('IM_PERF', 'Переферия'), ('CN_CPU', 'ЦП'), ('CN_RAM', 'ОЗУ'), ('CN_GPU', 'Видеокарты'), ('CN_MB', 'Материнские платы'), ('CN_FAN', 'Охлаждение'), ('CN_ROM', 'Носители информации')], max_length=250, verbose_name='Под категория'),
        ),
    ]
