# Generated by Django 3.2.3 on 2021-05-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20210530_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='ProductImage',
            field=models.ImageField(blank=True, default='product_images/no-image.jpg', height_field='197', null=True, upload_to='product_images', verbose_name='Изображение', width_field='197'),
        ),
    ]
