# Generated by Django 3.2.3 on 2021-05-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_catalog_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='ProductId',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID товара'),
        ),
    ]
