# Generated by Django 3.2.3 on 2021-06-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20210606_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='ProductIsrail',
            field=models.IntegerField(default=0, verbose_name='Товар в наличии'),
        ),
    ]
