# Generated by Django 3.2.3 on 2021-05-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=50, verbose_name='Логин')),
                ('Password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('EmailField', models.EmailField(max_length=254, verbose_name='Почта')),
                ('Post', models.CharField(max_length=50, verbose_name='Должность')),
                ('FirstName', models.CharField(max_length=120, verbose_name='Имя')),
                ('SecondName', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('IsAdmin', models.BooleanField(verbose_name='Администратор')),
            ],
        ),
    ]
